version: '3'

services:

  teste-kabum-app:
    container_name: teste-kabum-app
    build:
      context: .docker
      dockerfile: Docker/Dockerfile
    image: teste-kabum
    depends_on:
      - teste-kabum-mysql
    volumes:
      - ./:/application:cached

  teste-kabum-nginx:
    container_name: teste-kabum-nginx
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
      - .docker/nginx/:/var/log/nginx/
    depends_on:
      - teste-kabum-app
      - teste-kabum-mysql

  teste-kabum-mysql:
    container_name: teste-kabum-mysql
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kabum
      - MYSQL_USER=kabum
      - MYSQL_PASSWORD=root
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - teste-kabum-mysql-data:/var/lib/mysql:cached

volumes:
  teste-kabum-mysql-data:
